/* Generated by VB & C#.NET Class Generator */

using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

public class t02_usuario
{
	#region Declarations
    pageBase pb = new pageBase();
	private string _t02_cd_usuario;
	private int _t01_cd_entidade;
    private int _t05_cd_parceiro;
	private string _nm_nome;
	private string _nm_cargo;
	private string _nm_email;
    private long _nu_telefone;
    private long _nu_celular;
	private string _pw_senha;
	private DateTime _dt_cadastro;
	private DateTime _dt_alterado;
	private bool _fl_ativa;
    private string _nm_cpf;
	private bool _found;
    private string _order;
	#endregion

	#region Properties

	public string t02_cd_usuario
	{
		get { return _t02_cd_usuario; }
		set { _t02_cd_usuario = value; }
	}

	public int t01_cd_entidade
	{
		get { return _t01_cd_entidade; }
		set { _t01_cd_entidade = value; }
	}
    
    public int t05_cd_parceiro
    {
        get { return _t05_cd_parceiro; }
        set { _t05_cd_parceiro = value; }
    }

	public string nm_nome
	{
		get { return _nm_nome; }
		set { _nm_nome = value; }
	}

	public string nm_cargo
	{
		get { return _nm_cargo; }
		set { _nm_cargo = value; }
	}

	public string nm_email
	{
		get { return _nm_email; }
		set { _nm_email = value; }
	}

	public long nu_telefone
	{
		get { return _nu_telefone; }
		set { _nu_telefone = value; }
	}

    public long nu_celular
	{
		get { return _nu_celular; }
		set { _nu_celular = value; }
	}

	public string pw_senha
	{
		get { return _pw_senha; }
		set { _pw_senha = value; }
	}

	public DateTime dt_cadastro
	{
		get { return _dt_cadastro; }
		set { _dt_cadastro = value; }
	}

	public DateTime dt_alterado
	{
		get { return _dt_alterado; }
		set { _dt_alterado = value; }
	}

	public bool fl_ativa
	{
		get { return _fl_ativa; }
		set { _fl_ativa = value; }
	}

    public string nm_cpf
    {
        get { return _nm_cpf; }
        set { _nm_cpf = value; }
    }

	public bool Found
	{
		get { return _found; }
	}
    public string order
    {
        get { return _order; }
        set { _order = value; }
    }
	#endregion

	#region Functions/Routines

	#region List

	public DataSet List()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlDataAdapter adp = new SqlDataAdapter("select t02.*,t01.nm_entidade, t05.nm_parceiro from t02_usuario t02 " +
            "left join t01_entidade t01 "+
            "on t02.t01_cd_entidade = t01.t01_cd_entidade left join t05_parceiro t05 on t02.t05_cd_parceiro = t05.t05_cd_parceiro " +
            "where t02.fl_ativa=@fl_ativa " + _order, sqlConn);
        adp.SelectCommand.Parameters.Add("@fl_ativa", SqlDbType.Bit).Value = _fl_ativa;
		DataSet ds = new DataSet();

		try
		{
			sqlConn.Open();
			adp.SelectCommand.CommandType = CommandType.Text;
			adp.Fill(ds);
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

		finally
		{
			sqlConn.Close();
			adp.Dispose();
			sqlConn.Dispose();
		}

		return ds;
	}


    public DataSet ListParceiro()
    {
        SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlDataAdapter adp = new SqlDataAdapter("select t05.nm_parceiro, t01.nm_entidade, "+
            "t02.* from t02_usuario t02  " +
            "left join t05_parceiro t05 " +
            "on t02.t05_cd_parceiro = t05.t05_cd_parceiro " +
            "left join t01_entidade t01 "+
            "on t02.t01_cd_entidade=t01.t01_cd_entidade "+
            "where t02.fl_ativa=@fl_ativa " + _order, sqlConn);
        adp.SelectCommand.Parameters.Add("@fl_ativa", SqlDbType.Bit).Value = _fl_ativa;
        DataSet ds = new DataSet();

        try
        {
            sqlConn.Open();
            adp.SelectCommand.CommandType = CommandType.Text;
            adp.Fill(ds);
        }

        catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); }

        finally
        {
            sqlConn.Close();
            adp.Dispose();
            sqlConn.Dispose();
        }

        return ds;
    }

    public DataSet ListComboProjeto()
    {
        SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlDataAdapter adp = new SqlDataAdapter("select * from t02_usuario where  "+
            " (t01_cd_entidade=@t01_cd_entidade or t05_cd_parceiro in " +
            " (select t05_cd_parceiro from t05_parceiro where t01_cd_entidade=@t01_cd_entidade)) " + _order, sqlConn);
        adp.SelectCommand.Parameters.Add("@t01_cd_entidade", SqlDbType.Int).Value = _t01_cd_entidade;
        DataSet ds = new DataSet();

        try
        {
            sqlConn.Open();
            adp.SelectCommand.CommandType = CommandType.Text;
            adp.Fill(ds);
        }

        catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

        finally
        {
            sqlConn.Close();
            adp.Dispose();
            sqlConn.Dispose();
        }

        return ds;
    }

    public DataSet ListLinha()
    {
        SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlDataAdapter adp = new SqlDataAdapter("select * from t02_usuario where  " +
            " t02_cd_usuario in (select t02_cd_usuario from t32_usuariolinha " +
            " where t01_cd_entidade = @t01_cd_entidade)" , sqlConn);
        adp.SelectCommand.Parameters.Add("@t01_cd_entidade", SqlDbType.Int).Value = _t01_cd_entidade;
        DataSet ds = new DataSet();

        try
        {
            sqlConn.Open();
            adp.SelectCommand.CommandType = CommandType.Text;
            adp.Fill(ds);
        }

        catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); }

        finally
        {
            sqlConn.Close();
            adp.Dispose();
            sqlConn.Dispose();
        }

        return ds;
    }

	#endregion

	#region Retrieve

	public void Retrieve()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
		SqlCommand cmd = new SqlCommand("select * from t02_usuario where t02_cd_usuario=@t02_cd_usuario", sqlConn);
        cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;
		SqlDataReader data;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			data = cmd.ExecuteReader();

			if (data.Read())
			{
				_found = true;
				if (!Convert.IsDBNull(data["t02_cd_usuario"])) _t02_cd_usuario = (string) data["t02_cd_usuario"];
				if (!Convert.IsDBNull(data["t01_cd_entidade"])) _t01_cd_entidade = (int) data["t01_cd_entidade"];
                if (!Convert.IsDBNull(data["t05_cd_parceiro"])) _t05_cd_parceiro = (int)data["t05_cd_parceiro"];
				if (!Convert.IsDBNull(data["nm_nome"])) _nm_nome = (string) data["nm_nome"];
				if (!Convert.IsDBNull(data["nm_cargo"])) _nm_cargo = (string) data["nm_cargo"];
				if (!Convert.IsDBNull(data["nm_email"])) _nm_email = (string) data["nm_email"];
				if (!Convert.IsDBNull(data["nu_telefone"])) _nu_telefone = (long) data["nu_telefone"];
				if (!Convert.IsDBNull(data["nu_celular"])) _nu_celular = (long) data["nu_celular"];
				if (!Convert.IsDBNull(data["pw_senha"])) _pw_senha = (string) data["pw_senha"];
				if (!Convert.IsDBNull(data["dt_cadastro"])) _dt_cadastro = (DateTime) data["dt_cadastro"];
				if (!Convert.IsDBNull(data["dt_alterado"])) _dt_alterado = (DateTime) data["dt_alterado"];
				if (!Convert.IsDBNull(data["fl_ativa"])) _fl_ativa = (bool) data["fl_ativa"];
                if (!Convert.IsDBNull(data["nm_cpf"])) _nm_cpf = (string)data["nm_cpf"];
			}
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}
	}
   
    public void RetrieveLogin()
    {
        SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("select t02.*, pwdcompare(@pw_senha, convert(nvarchar(50), pw_senha), 0) " +
            "as resultado from t02_usuario t02 where (t02_cd_usuario=@t02_cd_usuario) and (fl_ativa=1)", sqlConn);
        cmd.Parameters.Add("@pw_senha", SqlDbType.VarChar, 50).Value = _pw_senha;
        cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;

        SqlDataReader data;

        try
        {
            sqlConn.Open();
            //cmd.CommandType = CommandType.StoredProcedure;
            data = cmd.ExecuteReader();

            if (data.Read())
            {
                
                if (!Convert.IsDBNull(data["t02_cd_usuario"])) _t02_cd_usuario = (string)data["t02_cd_usuario"];
                if (!Convert.IsDBNull(data["t01_cd_entidade"])) _t01_cd_entidade = (int)data["t01_cd_entidade"];
                if (!Convert.IsDBNull(data["t05_cd_parceiro"])) _t05_cd_parceiro = (int)data["t05_cd_parceiro"];
                if (!Convert.IsDBNull(data["nm_nome"])) _nm_nome = (string)data["nm_nome"];
                //if (!Convert.IsDBNull(data["nm_cargo"])) _nm_cargo = (string)data["nm_cargo"];
                //if (!Convert.IsDBNull(data["nm_email"])) _nm_email = (string)data["nm_email"];
                //if (!Convert.IsDBNull(data["nu_telefone"])) _nu_telefone = (long)data["nu_telefone"];
                //if (!Convert.IsDBNull(data["nu_celular"])) _nu_celular = (long)data["nu_celular"];
                //if (!Convert.IsDBNull(data["pw_senha"])) _pw_senha = (string)data["pw_senha"];
                //if (!Convert.IsDBNull(data["dt_cadastro"])) _dt_cadastro = (DateTime)data["dt_cadastro"];
                //if (!Convert.IsDBNull(data["dt_alterado"])) _dt_alterado = (DateTime)data["dt_alterado"];
                //if (!Convert.IsDBNull(data["fl_ativa"])) _fl_ativa = (bool)data["fl_ativa"];

                if (!Convert.IsDBNull(data["resultado"]))
                {
                    if ((int)data["resultado"] == 1)
                    {
                        _found = true;
                    }
                    else
                    {
                        _found = false;
                    }

                }
            }
        }

        catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

        finally
        {
            sqlConn.Close();
            cmd.Dispose();
            sqlConn.Dispose();
        }
    }
	#endregion

	#region Save

	public bool Save()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
		SqlCommand cmd = new SqlCommand("insert into t02_usuario values("+
                                        "@t02_cd_usuario,"+
                                        "@t01_cd_entidade," +
                                        "@t05_cd_parceiro, "+
                                        "@nm_nome," +
                                        "@nm_cargo," +
                                        "@nm_email," +
                                        "@nu_telefone," +
                                        "@nu_celular," +
                                        "pwdencrypt(@pw_senha)," +
                                        "@dt_cadastro," +
                                        "@dt_alterado," +
                                        "@fl_ativa, @nm_cpf)", sqlConn);
		bool result;
		cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;
		cmd.Parameters.Add("@t01_cd_entidade", SqlDbType.Int).Value = _t01_cd_entidade;
        cmd.Parameters.Add("@t05_cd_parceiro", SqlDbType.Int).Value = _t05_cd_parceiro;
		cmd.Parameters.Add("@nm_nome", SqlDbType.VarChar, 200).Value = _nm_nome;
		cmd.Parameters.Add("@nm_cargo", SqlDbType.VarChar, 100).Value = _nm_cargo;
		cmd.Parameters.Add("@nm_email", SqlDbType.VarChar, 100).Value = _nm_email;
		cmd.Parameters.Add("@nu_telefone", SqlDbType.BigInt).Value = _nu_telefone;
		cmd.Parameters.Add("@nu_celular", SqlDbType.BigInt).Value = _nu_celular;
		cmd.Parameters.Add("@pw_senha", SqlDbType.VarChar, 50).Value = _pw_senha;
		cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
		cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;
		cmd.Parameters.Add("@fl_ativa", SqlDbType.Bit).Value = _fl_ativa;
        cmd.Parameters.Add("@nm_cpf", SqlDbType.VarChar, 100).Value = _nm_cpf;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#region Update

	public bool Update()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t02_usuario set t01_cd_entidade=@t01_cd_entidade,t05_cd_parceiro=@t05_cd_parceiro, " +
            "nm_nome=@nm_nome, nm_cargo=@nm_cargo, nm_email=@nm_email, nu_telefone=@nu_telefone,"+
            "nu_celular=@nu_celular, dt_alterado=@dt_alterado, nm_cpf=@nm_cpf where t02_cd_usuario=@t02_cd_usuario", sqlConn);
		bool result;

		cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;
		cmd.Parameters.Add("@t01_cd_entidade", SqlDbType.Int).Value = _t01_cd_entidade;
        cmd.Parameters.Add("@t05_cd_parceiro", SqlDbType.Int).Value = _t05_cd_parceiro;
		cmd.Parameters.Add("@nm_nome", SqlDbType.VarChar, 200).Value = _nm_nome;
		cmd.Parameters.Add("@nm_cargo", SqlDbType.VarChar, 100).Value = _nm_cargo;
		cmd.Parameters.Add("@nm_email", SqlDbType.VarChar, 100).Value = _nm_email;
		cmd.Parameters.Add("@nu_telefone", SqlDbType.BigInt).Value = _nu_telefone;
		cmd.Parameters.Add("@nu_celular", SqlDbType.BigInt).Value = _nu_celular;
		//cmd.Parameters.Add("@pw_senha", SqlDbType.VarChar, 50).Value = _pw_senha;
		//cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
		cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;
        cmd.Parameters.Add("@nm_cpf", SqlDbType.VarChar, 100).Value = _nm_cpf;
		//cmd.Parameters.Add("@fl_ativa", SqlDbType.Bit).Value = _fl_ativa;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}
    public bool UpdateDados()
    {
        SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t02_usuario set " +
            "nm_nome=@nm_nome, nm_cargo=@nm_cargo, nm_email=@nm_email, nu_telefone=@nu_telefone," +
            "nu_celular=@nu_celular, dt_alterado=@dt_alterado, nm_cpf=@nm_cpf where t02_cd_usuario=@t02_cd_usuario", sqlConn);
        bool result;

        cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;
        cmd.Parameters.Add("@t01_cd_entidade", SqlDbType.Int).Value = _t01_cd_entidade;
        cmd.Parameters.Add("@t05_cd_parceiro", SqlDbType.Int).Value = _t05_cd_parceiro;
        cmd.Parameters.Add("@nm_nome", SqlDbType.VarChar, 200).Value = _nm_nome;
        cmd.Parameters.Add("@nm_cargo", SqlDbType.VarChar, 100).Value = _nm_cargo;
        cmd.Parameters.Add("@nm_email", SqlDbType.VarChar, 100).Value = _nm_email;
        cmd.Parameters.Add("@nu_telefone", SqlDbType.BigInt).Value = _nu_telefone;
        cmd.Parameters.Add("@nu_celular", SqlDbType.BigInt).Value = _nu_celular;
        //cmd.Parameters.Add("@pw_senha", SqlDbType.VarChar, 50).Value = _pw_senha;
        //cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
        cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;
        //cmd.Parameters.Add("@fl_ativa", SqlDbType.Bit).Value = _fl_ativa;
        cmd.Parameters.Add("@nm_cpf", SqlDbType.VarChar, 100).Value = _nm_cpf;

        try
        {
            sqlConn.Open();
            cmd.CommandType = CommandType.Text;
            result = Convert.ToBoolean(cmd.ExecuteNonQuery());
        }

        catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

        finally
        {
            sqlConn.Close();
            cmd.Dispose();
            sqlConn.Dispose();
        }

        return result;
    }


    public bool UpdateDados2()
    {
        SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t02_usuario set " +
            "nm_nome=@nm_nome, nm_cargo=@nm_cargo, nm_email=@nm_email, nu_telefone=@nu_telefone," +
            "nu_celular=@nu_celular, dt_alterado=@dt_alterado where t02_cd_usuario=@t02_cd_usuario", sqlConn);
        bool result;

        cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;
        //cmd.Parameters.Add("@t01_cd_entidade", SqlDbType.Int).Value = _t01_cd_entidade;
        //cmd.Parameters.Add("@t05_cd_parceiro", SqlDbType.Int).Value = _t05_cd_parceiro;
        cmd.Parameters.Add("@nm_nome", SqlDbType.VarChar, 200).Value = _nm_nome;
        cmd.Parameters.Add("@nm_cargo", SqlDbType.VarChar, 100).Value = _nm_cargo;
        cmd.Parameters.Add("@nm_email", SqlDbType.VarChar, 100).Value = _nm_email;
        cmd.Parameters.Add("@nu_telefone", SqlDbType.BigInt).Value = _nu_telefone;
        cmd.Parameters.Add("@nu_celular", SqlDbType.BigInt).Value = _nu_celular;
        //cmd.Parameters.Add("@pw_senha", SqlDbType.VarChar, 50).Value = _pw_senha;
        //cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
        cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;
        //cmd.Parameters.Add("@fl_ativa", SqlDbType.Bit).Value = _fl_ativa;
        //cmd.Parameters.Add("@nm_cpf", SqlDbType.VarChar, 100).Value = _nm_cpf;

        try
        {
            sqlConn.Open();
            cmd.CommandType = CommandType.Text;
            result = Convert.ToBoolean(cmd.ExecuteNonQuery());
        }

        catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

        finally
        {
            sqlConn.Close();
            cmd.Dispose();
            sqlConn.Dispose();
        }

        return result;
    }

    public bool UpdateSenha()
    {
        SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t02_usuario set pw_senha=pwdencrypt(@pw_senha), dt_alterado=getdate() where t02_cd_usuario=@t02_cd_usuario", sqlConn);
        bool result;

        cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;
        cmd.Parameters.Add("@pw_senha", SqlDbType.VarChar, 50).Value = _pw_senha;

        try
        {
            sqlConn.Open();
            cmd.CommandType = CommandType.Text;
            result = Convert.ToBoolean(cmd.ExecuteNonQuery());
        }

        catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

        finally
        {
            sqlConn.Close();
            cmd.Dispose();
            sqlConn.Dispose();
        }

        return result;
    }
    
	#endregion

	#region Delete

	public bool Delete()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t02_usuario set fl_ativa=0, dt_alterado=getdate()  where t02_cd_usuario=@t02_cd_usuario", sqlConn);
        cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;
		bool result;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#endregion
}
