/* Generated by VB & C#.NET Class Generator */

using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

public class t07_restricao
{
	#region Declarations
    pageBase pb = new pageBase();
	private int _t07_cd_restricao;
	private int _t03_cd_projeto;
	private string _ds_restricao;
	private string _ds_medida;
	private string _ds_providencia;
	private DateTime _dt_superada;
	private DateTime _dt_limite;
	private DateTime _dt_cadastro;
	private DateTime _dt_alterado;
	private bool _fl_ativa;
    private string _order;
	private bool _found;

	#endregion

	#region Properties

	public int t07_cd_restricao
	{
		get { return _t07_cd_restricao; }
		set { _t07_cd_restricao = value; }
	}

	public int t03_cd_projeto
	{
		get { return _t03_cd_projeto; }
		set { _t03_cd_projeto = value; }
	}

	public string ds_restricao
	{
		get { return _ds_restricao; }
		set { _ds_restricao = value; }
	}

	public string ds_medida
	{
		get { return _ds_medida; }
		set { _ds_medida = value; }
	}

	public string ds_providencia
	{
		get { return _ds_providencia; }
		set { _ds_providencia = value; }
	}

	public DateTime dt_superada
	{
		get { return _dt_superada; }
		set { _dt_superada = value; }
	}

	public DateTime dt_limite
	{
		get { return _dt_limite; }
		set { _dt_limite = value; }
	}

	public DateTime dt_cadastro
	{
		get { return _dt_cadastro; }
		set { _dt_cadastro = value; }
	}

	public DateTime dt_alterado
	{
		get { return _dt_alterado; }
		set { _dt_alterado = value; }
	}

	public bool fl_ativa
	{
		get { return _fl_ativa; }
		set { _fl_ativa = value; }
	}
    
    public string order
    {
        get { return _order; }
        set { _order = value; }
    }

	public bool Found
	{
		get { return _found; }
	}

	#endregion

	#region Functions/Routines

	#region List

	public DataSet List()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlDataAdapter adp = new SqlDataAdapter("select * from t07_restricao where t03_cd_projeto=@t03_cd_projeto and fl_ativa=1 and dt_superada is null " + _order, sqlConn);
        adp.SelectCommand.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;
		DataSet ds = new DataSet();

		try
		{
			sqlConn.Open();
			adp.SelectCommand.CommandType = CommandType.Text;
			adp.Fill(ds);
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

		finally
		{
			sqlConn.Close();
			adp.Dispose();
			sqlConn.Dispose();
		}

		return ds;
	}

	#endregion

	#region Retrieve

	public void Retrieve()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("select * from t07_restricao where t07_cd_restricao=@t07_cd_restricao", sqlConn);
        cmd.Parameters.Add("@t07_cd_restricao", SqlDbType.Int).Value = _t07_cd_restricao;
		SqlDataReader data;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			data = cmd.ExecuteReader();

			if (data.Read())
			{
				_found = true;
				if (!Convert.IsDBNull(data["t07_cd_restricao"])) _t07_cd_restricao = (int) data["t07_cd_restricao"];
				if (!Convert.IsDBNull(data["t03_cd_projeto"])) _t03_cd_projeto = (int) data["t03_cd_projeto"];
				if (!Convert.IsDBNull(data["ds_restricao"])) _ds_restricao = (string) data["ds_restricao"];
				if (!Convert.IsDBNull(data["ds_medida"])) _ds_medida = (string) data["ds_medida"];
				if (!Convert.IsDBNull(data["ds_providencia"])) _ds_providencia = (string) data["ds_providencia"];
				if (!Convert.IsDBNull(data["dt_superada"])) _dt_superada = (DateTime) data["dt_superada"];
				if (!Convert.IsDBNull(data["dt_limite"])) _dt_limite = (DateTime) data["dt_limite"];
				if (!Convert.IsDBNull(data["dt_cadastro"])) _dt_cadastro = (DateTime) data["dt_cadastro"];
				if (!Convert.IsDBNull(data["dt_alterado"])) _dt_alterado = (DateTime) data["dt_alterado"];
				if (!Convert.IsDBNull(data["fl_ativa"])) _fl_ativa = (bool) data["fl_ativa"];
			}
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}
	}
    public void RetrieveCod()
    {
        SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("select * from t07_restricao where t03_cd_projeto=@t03_cd_projeto and fl_ativa=1 order by dt_cadastro desc", sqlConn);
        cmd.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;
        SqlDataReader data;

        try
        {
            sqlConn.Open();
            cmd.CommandType = CommandType.Text;
            data = cmd.ExecuteReader();

            if (data.Read())
            {
                _found = true;
                if (!Convert.IsDBNull(data["t07_cd_restricao"])) _t07_cd_restricao = (int)data["t07_cd_restricao"];
                if (!Convert.IsDBNull(data["t03_cd_projeto"])) _t03_cd_projeto = (int)data["t03_cd_projeto"];
                if (!Convert.IsDBNull(data["ds_restricao"])) _ds_restricao = (string)data["ds_restricao"];
                if (!Convert.IsDBNull(data["ds_medida"])) _ds_medida = (string)data["ds_medida"];
                if (!Convert.IsDBNull(data["ds_providencia"])) _ds_providencia = (string)data["ds_providencia"];
                if (!Convert.IsDBNull(data["dt_superada"])) _dt_superada = (DateTime)data["dt_superada"];
                if (!Convert.IsDBNull(data["dt_limite"])) _dt_limite = (DateTime)data["dt_limite"];
                if (!Convert.IsDBNull(data["dt_cadastro"])) _dt_cadastro = (DateTime)data["dt_cadastro"];
                if (!Convert.IsDBNull(data["dt_alterado"])) _dt_alterado = (DateTime)data["dt_alterado"];
                if (!Convert.IsDBNull(data["fl_ativa"])) _fl_ativa = (bool)data["fl_ativa"];
            }
        }

        catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); }

        finally
        {
            sqlConn.Close();
            cmd.Dispose();
            sqlConn.Dispose();
        }
    }
	#endregion

	#region Save

	public bool Save()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("insert into t07_restricao values(@t03_cd_projeto, @ds_restricao, @ds_medida, null, "+
        "null, @dt_limite,@dt_cadastro,@dt_alterado,1)", sqlConn);
		bool result;

		cmd.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;
		cmd.Parameters.Add("@ds_restricao", SqlDbType.Text).Value = _ds_restricao;
		cmd.Parameters.Add("@ds_medida", SqlDbType.Text).Value = _ds_medida;
		//cmd.Parameters.Add("@ds_providencia", SqlDbType.Text).Value = _ds_providencia;
		//cmd.Parameters.Add("@dt_superada", SqlDbType.DateTime).Value = _dt_superada;
		cmd.Parameters.Add("@dt_limite", SqlDbType.DateTime).Value = _dt_limite;
		cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
		cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;
		//cmd.Parameters.Add("@fl_ativa", SqlDbType.Bit).Value = _fl_ativa;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#region Update

	public bool Update()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t07_restricao set ds_restricao=@ds_restricao, ds_medida=@ds_medida, dt_limite=@dt_limite, "+
            "dt_alterado=@dt_alterado where t07_cd_restricao=@t07_cd_restricao", sqlConn);
		bool result;

		cmd.Parameters.Add("@t07_cd_restricao", SqlDbType.Int).Value = _t07_cd_restricao;
		cmd.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;
		cmd.Parameters.Add("@ds_restricao", SqlDbType.Text).Value = _ds_restricao;
		cmd.Parameters.Add("@ds_medida", SqlDbType.Text).Value = _ds_medida;
		//cmd.Parameters.Add("@ds_providencia", SqlDbType.Text).Value = _ds_providencia;
		//cmd.Parameters.Add("@dt_superada", SqlDbType.DateTime).Value = _dt_superada;
		cmd.Parameters.Add("@dt_limite", SqlDbType.DateTime).Value = _dt_limite;
		//cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
		cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;
		cmd.Parameters.Add("@fl_ativa", SqlDbType.Bit).Value = _fl_ativa;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

    public bool UpdateSuperar()
    {
        SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t07_restricao set dt_superada=@dt_superada, " +
            "dt_alterado=@dt_alterado where t07_cd_restricao=@t07_cd_restricao", sqlConn);
        bool result;

        cmd.Parameters.Add("@t07_cd_restricao", SqlDbType.Int).Value = _t07_cd_restricao;
        //cmd.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;
        //cmd.Parameters.Add("@ds_restricao", SqlDbType.Text).Value = _ds_restricao;
        //cmd.Parameters.Add("@ds_medida", SqlDbType.Text).Value = _ds_medida;
        //cmd.Parameters.Add("@ds_providencia", SqlDbType.Text).Value = _ds_providencia;
        cmd.Parameters.Add("@dt_superada", SqlDbType.DateTime).Value = _dt_superada;
        //cmd.Parameters.Add("@dt_limite", SqlDbType.DateTime).Value = _dt_limite;
        //cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
        cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;
        cmd.Parameters.Add("@fl_ativa", SqlDbType.Bit).Value = _fl_ativa;

        try
        {
            sqlConn.Open();
            cmd.CommandType = CommandType.Text;
            result = Convert.ToBoolean(cmd.ExecuteNonQuery());
        }

        catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

        finally
        {
            sqlConn.Close();
            cmd.Dispose();
            sqlConn.Dispose();
        }

        return result;
    }
	#endregion

	#region Delete

	public bool Delete()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t07_restricao set fl_ativa=0, dt_alterado=getdate() where t07_cd_restricao=@t07_cd_restricao", sqlConn);
        cmd.Parameters.Add("@t07_cd_restricao", SqlDbType.Int).Value = _t07_cd_restricao;
		bool result;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#endregion
}
