/* Generated by VB & C#.NET Class Generator */

using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

public class t09_marco
{
	#region Declarations
    pageBase pb = new pageBase();
	private int _t09_cd_marco;
	private int _t08_cd_acao;
	private string _t02_cd_usuario;
	private string _ds_marco;
	private int _nu_esforco;
	private DateTime _dt_prevista;
	private DateTime _dt_realizada;
	private DateTime _dt_original;
	private string _ds_comentario;
	private string _fl_status;
	private int _nu_ordem;
	private DateTime _dt_cadastro;
	private DateTime _dt_alterado;
	private bool _fl_ativa;
    private bool _fl_original;
    private string _order;
	private bool _found;

	#endregion

	#region Properties

	public int t09_cd_marco
	{
		get { return _t09_cd_marco; }
		set { _t09_cd_marco = value; }
	}

	public int t08_cd_acao
	{
		get { return _t08_cd_acao; }
		set { _t08_cd_acao = value; }
	}

	public string t02_cd_usuario
	{
		get { return _t02_cd_usuario; }
		set { _t02_cd_usuario = value; }
	}

	public string ds_marco
	{
		get { return _ds_marco; }
		set { _ds_marco = value; }
	}

	public int nu_esforco
	{
		get { return _nu_esforco; }
		set { _nu_esforco = value; }
	}

	public DateTime dt_prevista
	{
		get { return _dt_prevista; }
		set { _dt_prevista = value; }
	}

	public DateTime dt_realizada
	{
		get { return _dt_realizada; }
		set { _dt_realizada = value; }
	}

	public DateTime dt_original
	{
		get { return _dt_original; }
		set { _dt_original = value; }
	}

	public string ds_comentario
	{
		get { return _ds_comentario; }
		set { _ds_comentario = value; }
	}

	public string fl_status
	{
		get { return _fl_status; }
		set { _fl_status = value; }
	}

	public int nu_ordem
	{
		get { return _nu_ordem; }
		set { _nu_ordem = value; }
	}

	public DateTime dt_cadastro
	{
		get { return _dt_cadastro; }
		set { _dt_cadastro = value; }
	}

	public DateTime dt_alterado
	{
		get { return _dt_alterado; }
		set { _dt_alterado = value; }
	}

	public bool fl_ativa
	{
		get { return _fl_ativa; }
		set { _fl_ativa = value; }
	}

    public bool fl_original
    {
        get { return _fl_original; }
        set { _fl_original = value; }
    }

    public string order
    {
        get { return _order; }
        set { _order = value; }
    }
	public bool Found
	{
		get { return _found; }
	}

	#endregion

	#region Functions/Routines

	#region List

	public DataSet List()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlDataAdapter adp = new SqlDataAdapter("select * from t09_marco where fl_ativa=1 and t08_cd_acao=@t08_cd_acao " + _order, sqlConn);
        adp.SelectCommand.Parameters.Add("@t08_cd_acao", SqlDbType.Int).Value = _t08_cd_acao;
		DataSet ds = new DataSet();

		try
		{
			sqlConn.Open();
			adp.SelectCommand.CommandType = CommandType.Text;
			adp.Fill(ds);
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

		finally
		{
			sqlConn.Close();
			adp.Dispose();
			sqlConn.Dispose();
		}

		return ds;
	}
    public DataSet ListStatus()
    {
        SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlDataAdapter adp = new SqlDataAdapter("select * from t09_marco where fl_ativa=1 " + _order, sqlConn);
        DataSet ds = new DataSet();

        try
        {
            sqlConn.Open();
            adp.SelectCommand.CommandType = CommandType.Text;
            adp.Fill(ds);
        }

        catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

        finally
        {
            sqlConn.Close();
            adp.Dispose();
            sqlConn.Dispose();
        }

        return ds;
    }
	#endregion

	#region Retrieve

	public void Retrieve()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("select * from t09_marco where t09_cd_marco=@t09_cd_marco", sqlConn);
        cmd.Parameters.Add("@t09_cd_marco", SqlDbType.Int).Value = _t09_cd_marco;
		SqlDataReader data;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			data = cmd.ExecuteReader();

			if (data.Read())
			{
				_found = true;
				if (!Convert.IsDBNull(data["t09_cd_marco"])) _t09_cd_marco = (int) data["t09_cd_marco"];
				if (!Convert.IsDBNull(data["t08_cd_acao"])) _t08_cd_acao = (int) data["t08_cd_acao"];
				if (!Convert.IsDBNull(data["t02_cd_usuario"])) _t02_cd_usuario = (string) data["t02_cd_usuario"];
				if (!Convert.IsDBNull(data["ds_marco"])) _ds_marco = (string) data["ds_marco"];
				if (!Convert.IsDBNull(data["nu_esforco"])) _nu_esforco = (int) data["nu_esforco"];
				if (!Convert.IsDBNull(data["dt_prevista"])) _dt_prevista = (DateTime) data["dt_prevista"];
				if (!Convert.IsDBNull(data["dt_realizada"])) _dt_realizada = (DateTime) data["dt_realizada"];
				if (!Convert.IsDBNull(data["dt_original"])) _dt_original = (DateTime) data["dt_original"];
				if (!Convert.IsDBNull(data["ds_comentario"])) _ds_comentario = (string) data["ds_comentario"];
				if (!Convert.IsDBNull(data["fl_status"])) _fl_status = (string) data["fl_status"];
				if (!Convert.IsDBNull(data["nu_ordem"])) _nu_ordem = (int) data["nu_ordem"];
				if (!Convert.IsDBNull(data["dt_cadastro"])) _dt_cadastro = (DateTime) data["dt_cadastro"];
				if (!Convert.IsDBNull(data["dt_alterado"])) _dt_alterado = (DateTime) data["dt_alterado"];
				if (!Convert.IsDBNull(data["fl_ativa"])) _fl_ativa = (bool) data["fl_ativa"];
                if (!Convert.IsDBNull(data["fl_original"])) _fl_original = (bool)data["fl_original"];
			}
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}
	}

	#endregion

	#region Save

	public bool Save()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("insert into t09_marco values(@t08_cd_acao, null,"+
            "'teste', 50, @dt_prevista, null, null, "+
            "@ds_comentario, @fl_status,null, @dt_cadastro, @dt_alterado, 1, @fl_original)", sqlConn);
		bool result;

		cmd.Parameters.Add("@t08_cd_acao", SqlDbType.Int).Value = _t08_cd_acao;
		//cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;
		cmd.Parameters.Add("@ds_marco", SqlDbType.Text).Value = _ds_marco;
		cmd.Parameters.Add("@nu_esforco", SqlDbType.Int).Value = _nu_esforco;
		cmd.Parameters.Add("@dt_prevista", SqlDbType.DateTime).Value = _dt_prevista;
		//cmd.Parameters.Add("@dt_realizada", SqlDbType.DateTime).Value = _dt_realizada;
		//cmd.Parameters.Add("@dt_original", SqlDbType.DateTime).Value = _dt_original;
		cmd.Parameters.Add("@ds_comentario", SqlDbType.Text).Value = _ds_comentario;
		cmd.Parameters.Add("@fl_status", SqlDbType.Char, 1).Value = _fl_status;
		//cmd.Parameters.Add("@nu_ordem", SqlDbType.Int).Value = _nu_ordem;
		cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
		cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;
		//cmd.Parameters.Add("@fl_ativa", SqlDbType.Bit).Value = _fl_ativa;
        cmd.Parameters.Add("@fl_original", SqlDbType.Bit).Value = _fl_original;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#region Update

	public bool Update()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t09_marco set "+
            "ds_marco=@ds_marco, nu_esforco=@nu_esforco, dt_prevista=@dt_prevista, ds_comentario=@ds_comentario, "+
            "dt_alterado=@dt_alterado "+ _order +" where t09_cd_marco=@t09_cd_marco", sqlConn);
		bool result;

		cmd.Parameters.Add("@t09_cd_marco", SqlDbType.Int).Value = _t09_cd_marco;
		//cmd.Parameters.Add("@t08_cd_acao", SqlDbType.Int).Value = _t08_cd_acao;
		//cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;
		cmd.Parameters.Add("@ds_marco", SqlDbType.Text).Value = _ds_marco;
		cmd.Parameters.Add("@nu_esforco", SqlDbType.Int).Value = _nu_esforco;
		cmd.Parameters.Add("@dt_prevista", SqlDbType.DateTime).Value = _dt_prevista;
		//cmd.Parameters.Add("@dt_realizada", SqlDbType.DateTime).Value = _dt_realizada;
		//cmd.Parameters.Add("@dt_original", SqlDbType.DateTime).Value = _dt_original;
		cmd.Parameters.Add("@ds_comentario", SqlDbType.Text).Value = _ds_comentario;
		//cmd.Parameters.Add("@fl_status", SqlDbType.Char, 1).Value = _fl_status;
		//cmd.Parameters.Add("@nu_ordem", SqlDbType.Int).Value = _nu_ordem;
		//cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
		cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;
		//cmd.Parameters.Add("@fl_ativa", SqlDbType.Bit).Value = _fl_ativa;
        //cmd.Parameters.Add("@fl_original", SqlDbType.Bit).Value = _fl_original;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}
    public bool UpdateCor()
    {
        SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t09_marco set " +
            "fl_status=@fl_status " + _order, sqlConn);
        bool result;

        cmd.Parameters.Add("@fl_status", SqlDbType.Char, 1).Value = _fl_status;

        try
        {
            sqlConn.Open();
            cmd.CommandType = CommandType.Text;
            result = Convert.ToBoolean(cmd.ExecuteNonQuery());
        }

        catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

        finally
        {
            sqlConn.Close();
            cmd.Dispose();
            sqlConn.Dispose();
        }

        return result;
    }

    public bool UpdateDesrealizar()
    {
        SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t09_marco set " +
            "dt_realizada=NULL where t09_cd_marco=@t09_cd_marco", sqlConn);
        bool result;

        cmd.Parameters.Add("@t09_cd_marco", SqlDbType.Int).Value = _t09_cd_marco;

        try
        {
            sqlConn.Open();
            cmd.CommandType = CommandType.Text;
            result = Convert.ToBoolean(cmd.ExecuteNonQuery());
        }

        catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

        finally
        {
            sqlConn.Close();
            cmd.Dispose();
            sqlConn.Dispose();
        }

        return result;
    }

	#endregion

	#region Delete

	public bool Delete()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t09_marco set fl_ativa=0 where t09_cd_marco=@t09_cd_marco", sqlConn);
        cmd.Parameters.Add("@t09_cd_marco", SqlDbType.Int).Value = _t09_cd_marco;
		bool result;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#endregion
}
