/* Generated by VB & C#.NET Class Generator */

using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

public class t18_documento
{
	#region Declarations
    pageBase pb = new pageBase();
	private int _t18_cd_documento;
	private int _t03_cd_projeto;
	private string _nm_documento;
	private string _ds_descricao;
	private string _nm_arquivo;
	private bool _fl_foto;
	private bool _fl_video;
	private bool _fl_cronograma;
	private bool _fl_outros;
	private DateTime _dt_cadastro;
	private DateTime _dt_alterado;
	private bool _fl_ativa;
    private string _order;
	private bool _found;

	#endregion

	#region Properties

	public int t18_cd_documento
	{
		get { return _t18_cd_documento; }
		set { _t18_cd_documento = value; }
	}

	public int t03_cd_projeto
	{
		get { return _t03_cd_projeto; }
		set { _t03_cd_projeto = value; }
	}

	public string nm_documento
	{
		get { return _nm_documento; }
		set { _nm_documento = value; }
	}

	public string ds_descricao
	{
		get { return _ds_descricao; }
		set { _ds_descricao = value; }
	}

	public string nm_arquivo
	{
		get { return _nm_arquivo; }
		set { _nm_arquivo = value; }
	}

	public bool fl_foto
	{
		get { return _fl_foto; }
		set { _fl_foto = value; }
	}

	public bool fl_video
	{
		get { return _fl_video; }
		set { _fl_video = value; }
	}

	public bool fl_cronograma
	{
		get { return _fl_cronograma; }
		set { _fl_cronograma = value; }
	}

	public bool fl_outros
	{
		get { return _fl_outros; }
		set { _fl_outros = value; }
	}

	public DateTime dt_cadastro
	{
		get { return _dt_cadastro; }
		set { _dt_cadastro = value; }
	}

	public DateTime dt_alterado
	{
		get { return _dt_alterado; }
		set { _dt_alterado = value; }
	}

	public bool fl_ativa
	{
		get { return _fl_ativa; }
		set { _fl_ativa = value; }
	}

    public string order
    {
        get { return _order; }
        set { _order = value; }
    }

	public bool Found
	{
		get { return _found; }
	}

	#endregion

	#region Functions/Routines

	#region List

	public DataSet List()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlDataAdapter adp = new SqlDataAdapter("select * from t18_documento where t03_cd_projeto=@t03_cd_projeto " +
            "and fl_foto=@fl_foto and fl_video=@fl_video and fl_cronograma=@fl_cronograma and fl_outros=@fl_outros and fl_ativa=1 " + _order, sqlConn);
        adp.SelectCommand.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;
        adp.SelectCommand.Parameters.Add("@fl_foto", SqlDbType.Bit).Value = _fl_foto;
        adp.SelectCommand.Parameters.Add("@fl_video", SqlDbType.Bit).Value = _fl_video;
        adp.SelectCommand.Parameters.Add("@fl_cronograma", SqlDbType.Bit).Value = _fl_cronograma;
        adp.SelectCommand.Parameters.Add("@fl_outros", SqlDbType.Bit).Value = _fl_outros;
		DataSet ds = new DataSet();

		try
		{
			sqlConn.Open();
			adp.SelectCommand.CommandType = CommandType.Text;
			adp.Fill(ds);
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

		finally
		{
			sqlConn.Close();
			adp.Dispose();
			sqlConn.Dispose();
		}

		return ds;
	}

	#endregion

	#region Retrieve

	public void Retrieve()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("select * from t18_documento where t18_cd_documento=@t18_cd_documento", sqlConn);
        cmd.Parameters.Add("@t18_cd_documento", SqlDbType.Int).Value = _t18_cd_documento;
		SqlDataReader data;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			data = cmd.ExecuteReader();

			if (data.Read())
			{
				_found = true;
				if (!Convert.IsDBNull(data["t18_cd_documento"])) _t18_cd_documento = (int) data["t18_cd_documento"];
				if (!Convert.IsDBNull(data["t03_cd_projeto"])) _t03_cd_projeto = (int) data["t03_cd_projeto"];
				if (!Convert.IsDBNull(data["nm_documento"])) _nm_documento = (string) data["nm_documento"];
				if (!Convert.IsDBNull(data["ds_descricao"])) _ds_descricao = (string) data["ds_descricao"];
				if (!Convert.IsDBNull(data["nm_arquivo"])) _nm_arquivo = (string) data["nm_arquivo"];
				if (!Convert.IsDBNull(data["fl_foto"])) _fl_foto = (bool) data["fl_foto"];
				if (!Convert.IsDBNull(data["fl_video"])) _fl_video = (bool) data["fl_video"];
				if (!Convert.IsDBNull(data["fl_cronograma"])) _fl_cronograma = (bool) data["fl_cronograma"];
				if (!Convert.IsDBNull(data["fl_outros"])) _fl_outros = (bool) data["fl_outros"];
				if (!Convert.IsDBNull(data["dt_cadastro"])) _dt_cadastro = (DateTime) data["dt_cadastro"];
				if (!Convert.IsDBNull(data["dt_alterado"])) _dt_alterado = (DateTime) data["dt_alterado"];
				if (!Convert.IsDBNull(data["fl_ativa"])) _fl_ativa = (bool) data["fl_ativa"];
			}
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}
	}

	#endregion

	#region Save

	public bool Save()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("insert into t18_documento values(@t03_cd_projeto, @nm_documento,"+
            "@ds_descricao, @nm_arquivo, @fl_foto, @fl_video, @fl_cronograma, @fl_outros, @dt_cadastro,@dt_alterado,1) ", sqlConn);
		bool result;

		cmd.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;
		cmd.Parameters.Add("@nm_documento", SqlDbType.VarChar, 1000).Value = _nm_documento;
		cmd.Parameters.Add("@ds_descricao", SqlDbType.Text).Value = _ds_descricao;
		cmd.Parameters.Add("@nm_arquivo", SqlDbType.VarChar, 500).Value = _nm_arquivo;
		cmd.Parameters.Add("@fl_foto", SqlDbType.Bit).Value = _fl_foto;
		cmd.Parameters.Add("@fl_video", SqlDbType.Bit).Value = _fl_video;
		cmd.Parameters.Add("@fl_cronograma", SqlDbType.Bit).Value = _fl_cronograma;
		cmd.Parameters.Add("@fl_outros", SqlDbType.Bit).Value = _fl_outros;
		cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
		cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;
		cmd.Parameters.Add("@fl_ativa", SqlDbType.Bit).Value = _fl_ativa;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#region Update

	public bool Update()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
		SqlCommand cmd = new SqlCommand("update t18_documento set "+
            "nm_documento=@nm_documento, dt_alterado=@dt_alterado " + _order +
            " where t18_cd_documento=@t18_cd_documento", sqlConn);
		bool result;

		cmd.Parameters.Add("@t18_cd_documento", SqlDbType.Int).Value = _t18_cd_documento;
		//cmd.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;
		cmd.Parameters.Add("@nm_documento", SqlDbType.VarChar, 1000).Value = _nm_documento;
		//cmd.Parameters.Add("@ds_descricao", SqlDbType.Text).Value = _ds_descricao;
		//cmd.Parameters.Add("@nm_arquivo", SqlDbType.VarChar, 500).Value = _nm_arquivo;
		//cmd.Parameters.Add("@fl_foto", SqlDbType.Bit).Value = _fl_foto;
		//cmd.Parameters.Add("@fl_video", SqlDbType.Bit).Value = _fl_video;
		//cmd.Parameters.Add("@fl_cronograma", SqlDbType.Bit).Value = _fl_cronograma;
		//cmd.Parameters.Add("@fl_outros", SqlDbType.Bit).Value = _fl_outros;
		//cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
		cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;
		//cmd.Parameters.Add("@fl_ativa", SqlDbType.Bit).Value = _fl_ativa;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#region Delete

	public bool Delete()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t18_documento set fl_ativa=0 where t18_cd_documento=@t18_cd_documento", sqlConn);
        cmd.Parameters.Add("@t18_cd_documento", SqlDbType.Int).Value = _t18_cd_documento;
		bool result;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#endregion
}
