/* Generated by VB & C#.NET Class Generator */

using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

public class t22_log
{
	#region Declarations
    pageBase pb = new pageBase();
    private int _t22_cd_log;
    private string _t02_cd_usuario;
    private int _t03_cd_projeto;
    private string _ds_log;
    private string _nm_tabela;
    private string _nm_comando;
    private string _nm_valor;
    private DateTime _dt_data;
    private bool _found;

	#endregion

	#region Properties

    public int t22_cd_log
    {
        get { return _t22_cd_log; }
        set { _t22_cd_log = value; }
    }

    public string t02_cd_usuario
    {
        get { return _t02_cd_usuario; }
        set { _t02_cd_usuario = value; }
    }

    public int t03_cd_projeto
    {
        get { return _t03_cd_projeto; }
        set { _t03_cd_projeto = value; }
    }

    public string ds_log
    {
        get { return _ds_log; }
        set { _ds_log = value; }
    }

    public string nm_tabela
    {
        get { return _nm_tabela; }
        set { _nm_tabela = value; }
    }

    public string nm_comando
    {
        get { return _nm_comando; }
        set { _nm_comando = value; }
    }

    public string nm_valor
    {
        get { return _nm_valor; }
        set { _nm_valor = value; }
    }

    public DateTime dt_data
    {
        get { return _dt_data; }
        set { _dt_data = value; }
    }

    public bool Found
    {
        get { return _found; }
    }

	#endregion

	#region Functions/Routines

	#region List

	public DataSet List()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
		SqlDataAdapter adp = new SqlDataAdapter("usp_t22_logList", sqlConn);
		DataSet ds = new DataSet();

		try
		{
			sqlConn.Open();
			adp.SelectCommand.CommandType = CommandType.Text;
			adp.Fill(ds);
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

		finally
		{
			sqlConn.Close();
			adp.Dispose();
			sqlConn.Dispose();
		}

		return ds;
	}

	#endregion

	#region Retrieve

	public void Retrieve()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
		SqlCommand cmd = new SqlCommand("usp_t22_logSelect", sqlConn);
		SqlDataReader data;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			data = cmd.ExecuteReader();

			if (data.Read())
			{
				_found = true;
                if (!Convert.IsDBNull(data["t22_cd_log"])) _t22_cd_log = (int)data["t22_cd_log"];
                if (!Convert.IsDBNull(data["t02_cd_usuario"])) _t02_cd_usuario = (string)data["t02_cd_usuario"];
                if (!Convert.IsDBNull(data["t03_cd_projeto"])) _t03_cd_projeto = (int)data["t03_cd_projeto"];
                if (!Convert.IsDBNull(data["ds_log"])) _ds_log = (string)data["ds_log"];
                if (!Convert.IsDBNull(data["nm_tabela"])) _nm_tabela = (string)data["nm_tabela"];
                if (!Convert.IsDBNull(data["nm_comando"])) _nm_comando = (string)data["nm_comando"];
                if (!Convert.IsDBNull(data["nm_valor"])) _nm_valor = (string)data["nm_valor"];
                if (!Convert.IsDBNull(data["dt_data"])) _dt_data = (DateTime)data["dt_data"];
			}
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}
	}

	#endregion

	#region Save

	public bool Save()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("insert into t22_log values(@t02_cd_usuario, @t03_cd_projeto, @ds_log,@nm_tabela, @nm_comando, @nm_valor, @dt_data)", sqlConn);
		bool result;

        cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;
        cmd.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;
        cmd.Parameters.Add("@ds_log", SqlDbType.Text).Value = _ds_log;
        cmd.Parameters.Add("@nm_tabela", SqlDbType.VarChar, 200).Value = _nm_tabela;
        cmd.Parameters.Add("@nm_comando", SqlDbType.VarChar, 200).Value = _nm_comando;
        cmd.Parameters.Add("@nm_valor", SqlDbType.VarChar, 200).Value = _nm_valor;
        cmd.Parameters.Add("@dt_data", SqlDbType.DateTime).Value = _dt_data;
		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#region Update

	public bool Update()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
		SqlCommand cmd = new SqlCommand("usp_t22_logUpdate", sqlConn);
		bool result;

        cmd.Parameters.Add("@t22_cd_log", SqlDbType.Int).Value = _t22_cd_log;
        cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;
        cmd.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;
        cmd.Parameters.Add("@ds_log", SqlDbType.Text).Value = _ds_log;
        cmd.Parameters.Add("@nm_tabela", SqlDbType.VarChar, 200).Value = _nm_tabela;
        cmd.Parameters.Add("@nm_comando", SqlDbType.VarChar, 200).Value = _nm_comando;
        cmd.Parameters.Add("@nm_valor", SqlDbType.VarChar, 200).Value = _nm_valor;
        cmd.Parameters.Add("@dt_data", SqlDbType.DateTime).Value = _dt_data;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#region Delete

	public bool Delete()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
		SqlCommand cmd = new SqlCommand("usp_t22_logDelete", sqlConn);
		bool result;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#endregion
}
