/* Generated by VB & C#.NET Class Generator */

using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

public class t23_noticia
{
	#region Declarations
    pageBase pb = new pageBase();
	private int _t23_cd_noticia;
    private int _t03_cd_projeto;
	private string _nm_noticia;
	private string _ds_noticia;
	private DateTime _dt_data;
	private DateTime _dt_cadastro;
	private DateTime _dt_alterado;
	private bool _fl_ativa;
    private string _nm_arquivo;
    private string _order;
	private bool _found;

	#endregion

	#region Properties

	public int t23_cd_noticia
	{
		get { return _t23_cd_noticia; }
		set { _t23_cd_noticia = value; }
	}

    public int t03_cd_projeto
    {
        get { return _t03_cd_projeto; }
        set { _t03_cd_projeto = value; }
    }

	public string nm_noticia
	{
		get { return _nm_noticia; }
		set { _nm_noticia = value; }
	}

	public string ds_noticia
	{
		get { return _ds_noticia; }
		set { _ds_noticia = value; }
	}

	public DateTime dt_data
	{
		get { return _dt_data; }
		set { _dt_data = value; }
	}

	public DateTime dt_cadastro
	{
		get { return _dt_cadastro; }
		set { _dt_cadastro = value; }
	}

	public DateTime dt_alterado
	{
		get { return _dt_alterado; }
		set { _dt_alterado = value; }
	}

	public bool fl_ativa
	{
		get { return _fl_ativa; }
		set { _fl_ativa = value; }
	}

    public string nm_arquivo
    {
        get { return _nm_arquivo; }
        set { _nm_arquivo = value; }
    }

    public string order
    {
        get { return _order; }
        set { _order = value; }
    }

	public bool Found
	{
		get { return _found; }
	}

	#endregion

	#region Functions/Routines

	#region List

	public DataSet List()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlDataAdapter adp = new SqlDataAdapter("select * from t23_noticia where t03_cd_projeto=@t03_cd_projeto and fl_ativa=1 " + _order, sqlConn);
        adp.SelectCommand.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;
		DataSet ds = new DataSet();

		try
		{
			sqlConn.Open();
			adp.SelectCommand.CommandType = CommandType.Text;
			adp.Fill(ds);
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

		finally
		{
			sqlConn.Close();
			adp.Dispose();
			sqlConn.Dispose();
		}

		return ds;
	}
    public DataSet ListProjetos()
    {
        SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlDataAdapter adp = new SqlDataAdapter("select * from t23_noticia where fl_ativa=1 " + _order, sqlConn);
        DataSet ds = new DataSet();

        try
        {
            sqlConn.Open();
            adp.SelectCommand.CommandType = CommandType.Text;
            adp.Fill(ds);
        }

        catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); }

        finally
        {
            sqlConn.Close();
            adp.Dispose();
            sqlConn.Dispose();
        }

        return ds;
    }

	#endregion

	#region Retrieve

	public void Retrieve()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("select * from t23_noticia where t23_cd_noticia=@t23_cd_noticia", sqlConn);
        cmd.Parameters.Add("@t23_cd_noticia", SqlDbType.Int).Value = _t23_cd_noticia;
		SqlDataReader data;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			data = cmd.ExecuteReader();

			if (data.Read())
			{
				_found = true;
				if (!Convert.IsDBNull(data["t23_cd_noticia"])) _t23_cd_noticia = (int) data["t23_cd_noticia"];
                if (!Convert.IsDBNull(data["t03_cd_projeto"])) _t03_cd_projeto = (int)data["t03_cd_projeto"];
				if (!Convert.IsDBNull(data["nm_noticia"])) _nm_noticia = (string) data["nm_noticia"];
				if (!Convert.IsDBNull(data["ds_noticia"])) _ds_noticia = (string) data["ds_noticia"];
				if (!Convert.IsDBNull(data["dt_data"])) _dt_data = (DateTime) data["dt_data"];
				if (!Convert.IsDBNull(data["dt_cadastro"])) _dt_cadastro = (DateTime) data["dt_cadastro"];
				if (!Convert.IsDBNull(data["dt_alterado"])) _dt_alterado = (DateTime) data["dt_alterado"];
				if (!Convert.IsDBNull(data["fl_ativa"])) _fl_ativa = (bool) data["fl_ativa"];
                if (!Convert.IsDBNull(data["nm_arquivo"])) _nm_arquivo = (string)data["nm_arquivo"];
			}
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}
	}

	#endregion

	#region Save

	public bool Save()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("insert into t23_noticia values(@t03_cd_projeto, @nm_noticia, @ds_noticia, @dt_data, @dt_cadastro, @dt_alterado, 1,@nm_arquivo)", sqlConn);
		bool result;

        cmd.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;
		cmd.Parameters.Add("@nm_noticia", SqlDbType.VarChar, 500).Value = _nm_noticia;
		cmd.Parameters.Add("@ds_noticia", SqlDbType.Text).Value = _ds_noticia;
		cmd.Parameters.Add("@dt_data", SqlDbType.DateTime).Value = _dt_data;
		cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
		cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;
		cmd.Parameters.Add("@fl_ativa", SqlDbType.Bit).Value = _fl_ativa;
        cmd.Parameters.Add("@nm_arquivo", SqlDbType.VarChar, 500).Value = _nm_arquivo;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#region Update

	public bool Update()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t23_noticia set t03_cd_projeto=@t03_cd_projeto, nm_noticia=@nm_noticia, ds_noticia=@ds_noticia, dt_data=@dt_data, dt_alterado=@dt_alterado " +
            _order + " where t23_cd_noticia=@t23_cd_noticia", sqlConn);
		bool result;

		cmd.Parameters.Add("@t23_cd_noticia", SqlDbType.Int).Value = _t23_cd_noticia;
        cmd.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;
		cmd.Parameters.Add("@nm_noticia", SqlDbType.VarChar, 500).Value = _nm_noticia;
		cmd.Parameters.Add("@ds_noticia", SqlDbType.Text).Value = _ds_noticia;
		cmd.Parameters.Add("@dt_data", SqlDbType.DateTime).Value = _dt_data;
		cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
		cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;
		cmd.Parameters.Add("@fl_ativa", SqlDbType.Bit).Value = _fl_ativa;
        //cmd.Parameters.Add("@nm_arquivo", SqlDbType.VarChar, 500).Value = _nm_arquivo;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#region Delete

	public bool Delete()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t23_noticia set fl_ativa=0 where t23_cd_noticia=@t23_cd_noticia", sqlConn);
        cmd.Parameters.Add("@t23_cd_noticia", SqlDbType.Int).Value = _t23_cd_noticia;
		bool result;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#endregion
}
