/* Generated by VB & C#.NET Class Generator */

using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

public class t26_usuarioperfil
{
	#region Declarations
    pageBase pb = new pageBase();
	private int _t26_cd_usuarioperfil;
	private string _t02_cd_usuario;
	private int _t25_cd_perfil;
	private DateTime _dt_cadastro;
	private DateTime _dt_alterado;
	private bool _found;

	#endregion

	#region Properties

	public int t26_cd_usuarioperfil
	{
		get { return _t26_cd_usuarioperfil; }
		set { _t26_cd_usuarioperfil = value; }
	}

	public string t02_cd_usuario
	{
		get { return _t02_cd_usuario; }
		set { _t02_cd_usuario = value; }
	}

	public int t25_cd_perfil
	{
		get { return _t25_cd_perfil; }
		set { _t25_cd_perfil = value; }
	}

	public DateTime dt_cadastro
	{
		get { return _dt_cadastro; }
		set { _dt_cadastro = value; }
	}

	public DateTime dt_alterado
	{
		get { return _dt_alterado; }
		set { _dt_alterado = value; }
	}

	public bool Found
	{
		get { return _found; }
	}

	#endregion

	#region Functions/Routines

	#region List

	public DataSet List()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlDataAdapter adp = new SqlDataAdapter("select * from t25_perfil where t25_cd_perfil in "+
            "(select t25_cd_perfil from t26_usuarioperfil where t02_cd_usuario='"+ _t02_cd_usuario +"')", sqlConn);
		DataSet ds = new DataSet();

        try
        {
            sqlConn.Open();
            adp.SelectCommand.CommandType = CommandType.Text;
            adp.Fill(ds);
        }

        catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

		finally
		{
			sqlConn.Close();
			adp.Dispose();
			sqlConn.Dispose();
		}

		return ds;
	}

	#endregion

	#region Retrieve

	public void Retrieve()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
		SqlCommand cmd = new SqlCommand("usp_t26_usuarioperfilSelect", sqlConn);
		SqlDataReader data;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			data = cmd.ExecuteReader();

			if (data.Read())
			{
				_found = true;
				if (!Convert.IsDBNull(data["t26_cd_usuarioperfil"])) _t26_cd_usuarioperfil = (int) data["t26_cd_usuarioperfil"];
				if (!Convert.IsDBNull(data["t02_cd_usuario"])) _t02_cd_usuario = (string) data["t02_cd_usuario"];
				if (!Convert.IsDBNull(data["t25_cd_perfil"])) _t25_cd_perfil = (int) data["t25_cd_perfil"];
				if (!Convert.IsDBNull(data["dt_cadastro"])) _dt_cadastro = (DateTime) data["dt_cadastro"];
				if (!Convert.IsDBNull(data["dt_alterado"])) _dt_alterado = (DateTime) data["dt_alterado"];
			}
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message);  }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}
	}

	#endregion

	#region Save

	public bool Save()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("insert into t26_usuarioperfil values(@t02_cd_usuario, @t25_cd_perfil, @dt_cadastro, @dt_alterado)", sqlConn);
		bool result;

		cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;
		cmd.Parameters.Add("@t25_cd_perfil", SqlDbType.Int).Value = _t25_cd_perfil;
		cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
		cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#region Update

	public bool Update()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
		SqlCommand cmd = new SqlCommand("usp_t26_usuarioperfilUpdate", sqlConn);
		bool result;

		cmd.Parameters.Add("@t26_cd_usuarioperfil", SqlDbType.Int).Value = _t26_cd_usuarioperfil;
		cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;
		cmd.Parameters.Add("@t25_cd_perfil", SqlDbType.Int).Value = _t25_cd_perfil;
		cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
		cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#region Delete

	public bool Delete()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("delete from t26_usuarioperfil where t02_cd_usuario=@t02_cd_usuario", sqlConn);
        cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;
		bool result;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch (Exception ex) { System.Web.HttpContext.Current.Response.Write(ex.Message); result = false; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#endregion
}
