/* Generated by VB & C#.NET Class Generator */

using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

public class t28_vlfinanceiro
{
	#region Declarations
    pageBase pb = new pageBase();
	private int _t28_cd_vlfinanceiro;
	private int _t11_cd_financeiro;
	private int _nu_ano;
	private decimal _vl_p1;
	private decimal _vl_p2;
	private decimal _vl_p3;
	private decimal _vl_p4;
	private decimal _vl_p5;
	private decimal _vl_p6;
	private decimal _vl_p7;
	private decimal _vl_p8;
	private decimal _vl_p9;
	private decimal _vl_p10;
	private decimal _vl_p11;
	private decimal _vl_p12;
	private decimal _vl_r1;
	private decimal _vl_r2;
	private decimal _vl_r3;
	private decimal _vl_r4;
	private decimal _vl_r5;
	private decimal _vl_r6;
	private decimal _vl_r7;
	private decimal _vl_r8;
	private decimal _vl_r9;
	private decimal _vl_r10;
	private decimal _vl_r11;
	private decimal _vl_r12;
	private DateTime _dt_cadastro;
	private DateTime _dt_alterado;
	private bool _found;

	#endregion

	#region Properties

	public int t28_cd_vlfinanceiro
	{
		get { return _t28_cd_vlfinanceiro; }
		set { _t28_cd_vlfinanceiro = value; }
	}

	public int t11_cd_financeiro
	{
		get { return _t11_cd_financeiro; }
		set { _t11_cd_financeiro = value; }
	}

	public int nu_ano
	{
		get { return _nu_ano; }
		set { _nu_ano = value; }
	}

	public decimal vl_p1
	{
		get { return _vl_p1; }
		set { _vl_p1 = value; }
	}

	public decimal vl_p2
	{
		get { return _vl_p2; }
		set { _vl_p2 = value; }
	}

	public decimal vl_p3
	{
		get { return _vl_p3; }
		set { _vl_p3 = value; }
	}

	public decimal vl_p4
	{
		get { return _vl_p4; }
		set { _vl_p4 = value; }
	}

	public decimal vl_p5
	{
		get { return _vl_p5; }
		set { _vl_p5 = value; }
	}

	public decimal vl_p6
	{
		get { return _vl_p6; }
		set { _vl_p6 = value; }
	}

	public decimal vl_p7
	{
		get { return _vl_p7; }
		set { _vl_p7 = value; }
	}

	public decimal vl_p8
	{
		get { return _vl_p8; }
		set { _vl_p8 = value; }
	}

	public decimal vl_p9
	{
		get { return _vl_p9; }
		set { _vl_p9 = value; }
	}

	public decimal vl_p10
	{
		get { return _vl_p10; }
		set { _vl_p10 = value; }
	}

	public decimal vl_p11
	{
		get { return _vl_p11; }
		set { _vl_p11 = value; }
	}

	public decimal vl_p12
	{
		get { return _vl_p12; }
		set { _vl_p12 = value; }
	}

	public decimal vl_r1
	{
		get { return _vl_r1; }
		set { _vl_r1 = value; }
	}

	public decimal vl_r2
	{
		get { return _vl_r2; }
		set { _vl_r2 = value; }
	}

	public decimal vl_r3
	{
		get { return _vl_r3; }
		set { _vl_r3 = value; }
	}

	public decimal vl_r4
	{
		get { return _vl_r4; }
		set { _vl_r4 = value; }
	}

	public decimal vl_r5
	{
		get { return _vl_r5; }
		set { _vl_r5 = value; }
	}

	public decimal vl_r6
	{
		get { return _vl_r6; }
		set { _vl_r6 = value; }
	}

	public decimal vl_r7
	{
		get { return _vl_r7; }
		set { _vl_r7 = value; }
	}

	public decimal vl_r8
	{
		get { return _vl_r8; }
		set { _vl_r8 = value; }
	}

	public decimal vl_r9
	{
		get { return _vl_r9; }
		set { _vl_r9 = value; }
	}

	public decimal vl_r10
	{
		get { return _vl_r10; }
		set { _vl_r10 = value; }
	}

	public decimal vl_r11
	{
		get { return _vl_r11; }
		set { _vl_r11 = value; }
	}

	public decimal vl_r12
	{
		get { return _vl_r12; }
		set { _vl_r12 = value; }
	}

	public DateTime dt_cadastro
	{
		get { return _dt_cadastro; }
		set { _dt_cadastro = value; }
	}

	public DateTime dt_alterado
	{
		get { return _dt_alterado; }
		set { _dt_alterado = value; }
	}

	public bool Found
	{
		get { return _found; }
	}

	#endregion

	#region Functions/Routines

	#region List

	public DataSet List()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlDataAdapter adp = new SqlDataAdapter("select * from t28_vlfinanceiro where t11_cd_financeiro=@t11_cd_financeiro", sqlConn);
        adp.SelectCommand.Parameters.Add("@t11_cd_financeiro", SqlDbType.Int).Value = _t11_cd_financeiro;
		DataSet ds = new DataSet();

		try
		{
			sqlConn.Open();
			adp.SelectCommand.CommandType = CommandType.Text;
			adp.Fill(ds);
		}

		catch { throw; }

		finally
		{
			sqlConn.Close();
			adp.Dispose();
			sqlConn.Dispose();
		}

		return ds;
	}

	#endregion

	#region Retrieve

	public void Retrieve()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("select * from t28_vlfinanceiro where t11_cd_financeiro=@t11_cd_financeiro and nu_ano=@nu_ano", sqlConn);
        cmd.Parameters.Add("@t11_cd_financeiro", SqlDbType.Int).Value = _t11_cd_financeiro;
        cmd.Parameters.Add("@nu_ano", SqlDbType.Int).Value = _nu_ano;
		SqlDataReader data;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			data = cmd.ExecuteReader();

			if (data.Read())
			{
				_found = true;
				if (!Convert.IsDBNull(data["t28_cd_vlfinanceiro"])) _t28_cd_vlfinanceiro = (int) data["t28_cd_vlfinanceiro"];
				if (!Convert.IsDBNull(data["t11_cd_financeiro"])) _t11_cd_financeiro = (int) data["t11_cd_financeiro"];
				if (!Convert.IsDBNull(data["nu_ano"])) _nu_ano = (int) data["nu_ano"];
				if (!Convert.IsDBNull(data["vl_p1"])) _vl_p1 = (decimal) data["vl_p1"];
				if (!Convert.IsDBNull(data["vl_p2"])) _vl_p2 = (decimal) data["vl_p2"];
				if (!Convert.IsDBNull(data["vl_p3"])) _vl_p3 = (decimal) data["vl_p3"];
				if (!Convert.IsDBNull(data["vl_p4"])) _vl_p4 = (decimal) data["vl_p4"];
				if (!Convert.IsDBNull(data["vl_p5"])) _vl_p5 = (decimal) data["vl_p5"];
				if (!Convert.IsDBNull(data["vl_p6"])) _vl_p6 = (decimal) data["vl_p6"];
				if (!Convert.IsDBNull(data["vl_p7"])) _vl_p7 = (decimal) data["vl_p7"];
				if (!Convert.IsDBNull(data["vl_p8"])) _vl_p8 = (decimal) data["vl_p8"];
				if (!Convert.IsDBNull(data["vl_p9"])) _vl_p9 = (decimal) data["vl_p9"];
				if (!Convert.IsDBNull(data["vl_p10"])) _vl_p10 = (decimal) data["vl_p10"];
				if (!Convert.IsDBNull(data["vl_p11"])) _vl_p11 = (decimal) data["vl_p11"];
				if (!Convert.IsDBNull(data["vl_p12"])) _vl_p12 = (decimal) data["vl_p12"];
				if (!Convert.IsDBNull(data["vl_r1"])) _vl_r1 = (decimal) data["vl_r1"];
				if (!Convert.IsDBNull(data["vl_r2"])) _vl_r2 = (decimal) data["vl_r2"];
				if (!Convert.IsDBNull(data["vl_r3"])) _vl_r3 = (decimal) data["vl_r3"];
				if (!Convert.IsDBNull(data["vl_r4"])) _vl_r4 = (decimal) data["vl_r4"];
				if (!Convert.IsDBNull(data["vl_r5"])) _vl_r5 = (decimal) data["vl_r5"];
				if (!Convert.IsDBNull(data["vl_r6"])) _vl_r6 = (decimal) data["vl_r6"];
				if (!Convert.IsDBNull(data["vl_r7"])) _vl_r7 = (decimal) data["vl_r7"];
				if (!Convert.IsDBNull(data["vl_r8"])) _vl_r8 = (decimal) data["vl_r8"];
				if (!Convert.IsDBNull(data["vl_r9"])) _vl_r9 = (decimal) data["vl_r9"];
				if (!Convert.IsDBNull(data["vl_r10"])) _vl_r10 = (decimal) data["vl_r10"];
				if (!Convert.IsDBNull(data["vl_r11"])) _vl_r11 = (decimal) data["vl_r11"];
				if (!Convert.IsDBNull(data["vl_r12"])) _vl_r12 = (decimal) data["vl_r12"];
				if (!Convert.IsDBNull(data["dt_cadastro"])) _dt_cadastro = (DateTime) data["dt_cadastro"];
				if (!Convert.IsDBNull(data["dt_alterado"])) _dt_alterado = (DateTime) data["dt_alterado"];
			}
		}

		catch { throw; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}
	}

	#endregion

	#region Save

	public bool Save()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("insert into t28_vlfinanceiro values(@t11_cd_financeiro, @nu_ano, @vl_p1, @vl_p2, @vl_p3, @vl_p4, @vl_p5, @vl_p6, @vl_p7, @vl_p8, @vl_p9, @vl_p10, @vl_p11, @vl_p12, @vl_r1, @vl_r2, @vl_r3, @vl_r4, @vl_r5, @vl_r6, @vl_r7, @vl_r8, @vl_r9, @vl_r10, @vl_r11, @vl_r12, getdate(), getdate())", sqlConn);
		bool result;

		cmd.Parameters.Add("@t11_cd_financeiro", SqlDbType.Int).Value = _t11_cd_financeiro;
		cmd.Parameters.Add("@nu_ano", SqlDbType.Int).Value = _nu_ano;
		cmd.Parameters.Add("@vl_p1", SqlDbType.Decimal).Value = _vl_p1;
		cmd.Parameters.Add("@vl_p2", SqlDbType.Decimal).Value = _vl_p2;
		cmd.Parameters.Add("@vl_p3", SqlDbType.Decimal).Value = _vl_p3;
		cmd.Parameters.Add("@vl_p4", SqlDbType.Decimal).Value = _vl_p4;
		cmd.Parameters.Add("@vl_p5", SqlDbType.Decimal).Value = _vl_p5;
		cmd.Parameters.Add("@vl_p6", SqlDbType.Decimal).Value = _vl_p6;
		cmd.Parameters.Add("@vl_p7", SqlDbType.Decimal).Value = _vl_p7;
		cmd.Parameters.Add("@vl_p8", SqlDbType.Decimal).Value = _vl_p8;
		cmd.Parameters.Add("@vl_p9", SqlDbType.Decimal).Value = _vl_p9;
		cmd.Parameters.Add("@vl_p10", SqlDbType.Decimal).Value = _vl_p10;
		cmd.Parameters.Add("@vl_p11", SqlDbType.Decimal).Value = _vl_p11;
		cmd.Parameters.Add("@vl_p12", SqlDbType.Decimal).Value = _vl_p12;
		cmd.Parameters.Add("@vl_r1", SqlDbType.Decimal).Value = _vl_r1;
		cmd.Parameters.Add("@vl_r2", SqlDbType.Decimal).Value = _vl_r2;
		cmd.Parameters.Add("@vl_r3", SqlDbType.Decimal).Value = _vl_r3;
		cmd.Parameters.Add("@vl_r4", SqlDbType.Decimal).Value = _vl_r4;
		cmd.Parameters.Add("@vl_r5", SqlDbType.Decimal).Value = _vl_r5;
		cmd.Parameters.Add("@vl_r6", SqlDbType.Decimal).Value = _vl_r6;
		cmd.Parameters.Add("@vl_r7", SqlDbType.Decimal).Value = _vl_r7;
		cmd.Parameters.Add("@vl_r8", SqlDbType.Decimal).Value = _vl_r8;
		cmd.Parameters.Add("@vl_r9", SqlDbType.Decimal).Value = _vl_r9;
		cmd.Parameters.Add("@vl_r10", SqlDbType.Decimal).Value = _vl_r10;
		cmd.Parameters.Add("@vl_r11", SqlDbType.Decimal).Value = _vl_r11;
		cmd.Parameters.Add("@vl_r12", SqlDbType.Decimal).Value = _vl_r12;
		//cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
		//cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch { throw; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#region Update

	public bool Update()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t28_vlfinanceiro set where", sqlConn);
		bool result;

		cmd.Parameters.Add("@t28_cd_vlfinanceiro", SqlDbType.Int).Value = _t28_cd_vlfinanceiro;
		cmd.Parameters.Add("@t11_cd_financeiro", SqlDbType.Int).Value = _t11_cd_financeiro;
		cmd.Parameters.Add("@nu_ano", SqlDbType.Int).Value = _nu_ano;
		cmd.Parameters.Add("@vl_p1", SqlDbType.Decimal).Value = _vl_p1;
		cmd.Parameters.Add("@vl_p2", SqlDbType.Decimal).Value = _vl_p2;
		cmd.Parameters.Add("@vl_p3", SqlDbType.Decimal).Value = _vl_p3;
		cmd.Parameters.Add("@vl_p4", SqlDbType.Decimal).Value = _vl_p4;
		cmd.Parameters.Add("@vl_p5", SqlDbType.Decimal).Value = _vl_p5;
		cmd.Parameters.Add("@vl_p6", SqlDbType.Decimal).Value = _vl_p6;
		cmd.Parameters.Add("@vl_p7", SqlDbType.Decimal).Value = _vl_p7;
		cmd.Parameters.Add("@vl_p8", SqlDbType.Decimal).Value = _vl_p8;
		cmd.Parameters.Add("@vl_p9", SqlDbType.Decimal).Value = _vl_p9;
		cmd.Parameters.Add("@vl_p10", SqlDbType.Decimal).Value = _vl_p10;
		cmd.Parameters.Add("@vl_p11", SqlDbType.Decimal).Value = _vl_p11;
		cmd.Parameters.Add("@vl_p12", SqlDbType.Decimal).Value = _vl_p12;
		cmd.Parameters.Add("@vl_r1", SqlDbType.Decimal).Value = _vl_r1;
		cmd.Parameters.Add("@vl_r2", SqlDbType.Decimal).Value = _vl_r2;
		cmd.Parameters.Add("@vl_r3", SqlDbType.Decimal).Value = _vl_r3;
		cmd.Parameters.Add("@vl_r4", SqlDbType.Decimal).Value = _vl_r4;
		cmd.Parameters.Add("@vl_r5", SqlDbType.Decimal).Value = _vl_r5;
		cmd.Parameters.Add("@vl_r6", SqlDbType.Decimal).Value = _vl_r6;
		cmd.Parameters.Add("@vl_r7", SqlDbType.Decimal).Value = _vl_r7;
		cmd.Parameters.Add("@vl_r8", SqlDbType.Decimal).Value = _vl_r8;
		cmd.Parameters.Add("@vl_r9", SqlDbType.Decimal).Value = _vl_r9;
		cmd.Parameters.Add("@vl_r10", SqlDbType.Decimal).Value = _vl_r10;
		cmd.Parameters.Add("@vl_r11", SqlDbType.Decimal).Value = _vl_r11;
		cmd.Parameters.Add("@vl_r12", SqlDbType.Decimal).Value = _vl_r12;
		cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;
		cmd.Parameters.Add("@dt_alterado", SqlDbType.DateTime).Value = _dt_alterado;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch { throw; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#region Delete

	public bool Delete()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("delete from t28_vlfinanceiro where t11_cd_financeiro=@t11_cd_financeiro", sqlConn);
        cmd.Parameters.Add("@t11_cd_financeiro", SqlDbType.Int).Value = _t11_cd_financeiro;
		bool result;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch { throw; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#endregion
}
