/* Generated by VB & C#.NET Class Generator */

using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

public class t29_acaorestricao
{
	#region Declarations
    pageBase pb = new pageBase();
	private int _t29_cd_acaorestricao;
	private int _t07_cd_restricao;
	private int _t08_cd_acao;
	private DateTime _dt_cadastro;
	private bool _found;

	#endregion

	#region Properties

	public int t29_cd_acaorestricao
	{
		get { return _t29_cd_acaorestricao; }
		set { _t29_cd_acaorestricao = value; }
	}

	public int t07_cd_restricao
	{
		get { return _t07_cd_restricao; }
		set { _t07_cd_restricao = value; }
	}

	public int t08_cd_acao
	{
		get { return _t08_cd_acao; }
		set { _t08_cd_acao = value; }
	}

	public DateTime dt_cadastro
	{
		get { return _dt_cadastro; }
		set { _dt_cadastro = value; }
	}

	public bool Found
	{
		get { return _found; }
	}

	#endregion

	#region Functions/Routines

	#region List

	public DataSet List()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
		SqlDataAdapter adp = new SqlDataAdapter("select * from t29_acaorestricao where", sqlConn);
		DataSet ds = new DataSet();

		try
		{
			sqlConn.Open();
			adp.SelectCommand.CommandType = CommandType.Text;
			adp.Fill(ds);
		}

		catch { throw; }

		finally
		{
			sqlConn.Close();
			adp.Dispose();
			sqlConn.Dispose();
		}

		return ds;
	}

	#endregion

	#region Retrieve

	public void Retrieve()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("select * from t29_acaorestricao where t07_cd_restricao=@t07_cd_restricao", sqlConn);
        cmd.Parameters.Add("@t07_cd_restricao", SqlDbType.Int).Value = _t07_cd_restricao;
		SqlDataReader data;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			data = cmd.ExecuteReader();

			if (data.Read())
			{
				_found = true;
				if (!Convert.IsDBNull(data["t29_cd_acaorestricao"])) _t29_cd_acaorestricao = (int) data["t29_cd_acaorestricao"];
				if (!Convert.IsDBNull(data["t07_cd_restricao"])) _t07_cd_restricao = (int) data["t07_cd_restricao"];
				if (!Convert.IsDBNull(data["t08_cd_acao"])) _t08_cd_acao = (int) data["t08_cd_acao"];
				if (!Convert.IsDBNull(data["dt_cadastro"])) _dt_cadastro = (DateTime) data["dt_cadastro"];
			}
		}

		catch { throw; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}
	}

    public void RetrieveAcao()
    {
        SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("select * from t29_acaorestricao where t08_cd_acao=@t08_cd_acao", sqlConn);
        cmd.Parameters.Add("@t08_cd_acao", SqlDbType.Int).Value = _t08_cd_acao;
        SqlDataReader data;

        try
        {
            sqlConn.Open();
            cmd.CommandType = CommandType.Text;
            data = cmd.ExecuteReader();

            if (data.Read())
            {
                _found = true;
                if (!Convert.IsDBNull(data["t29_cd_acaorestricao"])) _t29_cd_acaorestricao = (int)data["t29_cd_acaorestricao"];
                if (!Convert.IsDBNull(data["t07_cd_restricao"])) _t07_cd_restricao = (int)data["t07_cd_restricao"];
                if (!Convert.IsDBNull(data["t08_cd_acao"])) _t08_cd_acao = (int)data["t08_cd_acao"];
                if (!Convert.IsDBNull(data["dt_cadastro"])) _dt_cadastro = (DateTime)data["dt_cadastro"];
            }
        }

        catch { throw; }

        finally
        {
            sqlConn.Close();
            cmd.Dispose();
            sqlConn.Dispose();
        }
    }
	#endregion

	#region Save

	public bool Save()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("insert into t29_acaorestricao values(@t07_cd_restricao, @t08_cd_acao, getdate())", sqlConn);
		bool result;

		cmd.Parameters.Add("@t07_cd_restricao", SqlDbType.Int).Value = _t07_cd_restricao;
		cmd.Parameters.Add("@t08_cd_acao", SqlDbType.Int).Value = _t08_cd_acao;
		//cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch { throw; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#region Update

	public bool Update()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
		SqlCommand cmd = new SqlCommand("update t29_acaorestricao set where", sqlConn);
		bool result;

		cmd.Parameters.Add("@t29_cd_acaorestricao", SqlDbType.Int).Value = _t29_cd_acaorestricao;
		cmd.Parameters.Add("@t07_cd_restricao", SqlDbType.Int).Value = _t07_cd_restricao;
		cmd.Parameters.Add("@t08_cd_acao", SqlDbType.Int).Value = _t08_cd_acao;
		cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch { throw; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#region Delete

	public bool Delete()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("delete from t29_acaorestricao where t07_cd_restricao=@t07_cd_restricao", sqlConn);
        cmd.Parameters.Add("@t07_cd_restricao", SqlDbType.Int).Value = _t07_cd_restricao;

		bool result;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch { throw; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#endregion
}
