/* Generated by VB & C#.NET Class Generator */

using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

public class t31_acaofase
{
	#region Declarations
    pageBase pb = new pageBase();
	private int _t31_cd_acaofase;
	private int _t30_cd_projetofase;
	private string _t02_cd_usuario;
	private int _t03_cd_projeto;
	private string _nm_acao;
	private string _ds_acao;
	private DateTime _dt_inicio;
	private DateTime _dt_fim;
	private DateTime _dt_original;
	private decimal _vl_previsto;
	private decimal _vl_realizado;
	private DateTime _dt_cadastro;
	private bool _found;

	#endregion

	#region Properties

	public int t31_cd_acaofase
	{
		get { return _t31_cd_acaofase; }
		set { _t31_cd_acaofase = value; }
	}

	public int t30_cd_projetofase
	{
		get { return _t30_cd_projetofase; }
		set { _t30_cd_projetofase = value; }
	}

	public string t02_cd_usuario
	{
		get { return _t02_cd_usuario; }
		set { _t02_cd_usuario = value; }
	}

	public int t03_cd_projeto
	{
		get { return _t03_cd_projeto; }
		set { _t03_cd_projeto = value; }
	}

	public string nm_acao
	{
		get { return _nm_acao; }
		set { _nm_acao = value; }
	}

	public string ds_acao
	{
		get { return _ds_acao; }
		set { _ds_acao = value; }
	}

	public DateTime dt_inicio
	{
		get { return _dt_inicio; }
		set { _dt_inicio = value; }
	}

	public DateTime dt_fim
	{
		get { return _dt_fim; }
		set { _dt_fim = value; }
	}

	public DateTime dt_original
	{
		get { return _dt_original; }
		set { _dt_original = value; }
	}

	public decimal vl_previsto
	{
		get { return _vl_previsto; }
		set { _vl_previsto = value; }
	}

	public decimal vl_realizado
	{
		get { return _vl_realizado; }
		set { _vl_realizado = value; }
	}

	public DateTime dt_cadastro
	{
		get { return _dt_cadastro; }
		set { _dt_cadastro = value; }
	}

	public bool Found
	{
		get { return _found; }
	}

	#endregion

	#region Functions/Routines

	#region List

	public DataSet List()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
		SqlDataAdapter adp = new SqlDataAdapter("select * from t31_acaofase where", sqlConn);
		DataSet ds = new DataSet();

		try
		{
			sqlConn.Open();
			adp.SelectCommand.CommandType = CommandType.Text;
			adp.Fill(ds);
		}

		catch { throw; }

		finally
		{
			sqlConn.Close();
			adp.Dispose();
			sqlConn.Dispose();
		}

		return ds;
	}

    public DataSet ListAcoes()
    {
        SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlDataAdapter adp = new SqlDataAdapter("select t08.*, "+
        "(select sum(vl_p1 + vl_p2+ vl_p3+ vl_p4+ vl_p5+ vl_p6+ vl_p7+ vl_p8+ vl_p9+ vl_p10+ vl_p11+ vl_p12) from t11_financeiro t11 left join t28_vlfinanceiro t28 on t11.t11_cd_financeiro = t28.t11_cd_financeiro where t11.t08_cd_acao=t08.t08_cd_acao) as vl_previsto, "+
        "(select sum(vl_r1 + vl_r2+ vl_r3+ vl_r4+ vl_r5+ vl_r6+ vl_r7+ vl_r8+ vl_r9+ vl_r10+ vl_r11+ vl_r12) from t11_financeiro t11 left join t28_vlfinanceiro t28 on t11.t11_cd_financeiro = t28.t11_cd_financeiro where t11.t08_cd_acao=t08.t08_cd_acao) as vl_realizado  "+
        "from t08_acao t08  "+
        "where fl_ativa=1 and t03_cd_projeto=@t03_cd_projeto", sqlConn);
        adp.SelectCommand.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;
        DataSet ds = new DataSet();
        
        try
        {
            sqlConn.Open();
            adp.SelectCommand.CommandType = CommandType.Text;
            adp.Fill(ds);
        }

        catch { throw; }

        finally
        {
            sqlConn.Close();
            adp.Dispose();
            sqlConn.Dispose();
        }

        return ds;
    }

	#endregion

	#region Retrieve

	public void Retrieve()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
		SqlCommand cmd = new SqlCommand("select * from t31_acaofase where", sqlConn);
		SqlDataReader data;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			data = cmd.ExecuteReader();

			if (data.Read())
			{
				_found = true;
				if (!Convert.IsDBNull(data["t31_cd_acaofase"])) _t31_cd_acaofase = (int) data["t31_cd_acaofase"];
				if (!Convert.IsDBNull(data["t30_cd_projetofase"])) _t30_cd_projetofase = (int) data["t30_cd_projetofase"];
				if (!Convert.IsDBNull(data["t02_cd_usuario"])) _t02_cd_usuario = (string) data["t02_cd_usuario"];
				if (!Convert.IsDBNull(data["t03_cd_projeto"])) _t03_cd_projeto = (int) data["t03_cd_projeto"];
				if (!Convert.IsDBNull(data["nm_acao"])) _nm_acao = (string) data["nm_acao"];
				if (!Convert.IsDBNull(data["ds_acao"])) _ds_acao = (string) data["ds_acao"];
				if (!Convert.IsDBNull(data["dt_inicio"])) _dt_inicio = (DateTime) data["dt_inicio"];
				if (!Convert.IsDBNull(data["dt_fim"])) _dt_fim = (DateTime) data["dt_fim"];
				if (!Convert.IsDBNull(data["dt_original"])) _dt_original = (DateTime) data["dt_original"];
				if (!Convert.IsDBNull(data["vl_previsto"])) _vl_previsto = (decimal) data["vl_previsto"];
				if (!Convert.IsDBNull(data["vl_realizado"])) _vl_realizado = (decimal) data["vl_realizado"];
				if (!Convert.IsDBNull(data["dt_cadastro"])) _dt_cadastro = (DateTime) data["dt_cadastro"];
			}
		}

		catch { throw; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}
	}

	#endregion

	#region Save

	public bool Save()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("insert into t31_acaofase values(@t30_cd_projetofase, "+
            "@t02_cd_usuario, " +
            "@t03_cd_projeto, " +
            "@nm_acao, " +
            "@ds_acao, " +
            "@dt_inicio, " +
            "@dt_fim, " +
            "@dt_original, " +
            "@vl_previsto, " +
            "@vl_realizado, " +
            "getdate())", sqlConn);
		bool result;

		cmd.Parameters.Add("@t30_cd_projetofase", SqlDbType.Int).Value = _t30_cd_projetofase;
		cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;
		cmd.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;
		cmd.Parameters.Add("@nm_acao", SqlDbType.VarChar, 500).Value = _nm_acao;
		cmd.Parameters.Add("@ds_acao", SqlDbType.Text).Value = _ds_acao;
		cmd.Parameters.Add("@dt_inicio", SqlDbType.DateTime).Value = _dt_inicio;
		cmd.Parameters.Add("@dt_fim", SqlDbType.DateTime).Value = _dt_fim;
		cmd.Parameters.Add("@dt_original", SqlDbType.DateTime).Value = _dt_original;
		cmd.Parameters.Add("@vl_previsto", SqlDbType.Decimal).Value = _vl_previsto;
		cmd.Parameters.Add("@vl_realizado", SqlDbType.Decimal).Value = _vl_realizado;
		//cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch { throw; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#region Update

	public bool Update()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
		SqlCommand cmd = new SqlCommand("update t31_acaofase set where", sqlConn);
		bool result;

		cmd.Parameters.Add("@t31_cd_acaofase", SqlDbType.Int).Value = _t31_cd_acaofase;
		cmd.Parameters.Add("@t30_cd_projetofase", SqlDbType.Int).Value = _t30_cd_projetofase;
		cmd.Parameters.Add("@t02_cd_usuario", SqlDbType.VarChar, 20).Value = _t02_cd_usuario;
		cmd.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;
		cmd.Parameters.Add("@nm_acao", SqlDbType.VarChar, 500).Value = _nm_acao;
		cmd.Parameters.Add("@ds_acao", SqlDbType.Text).Value = _ds_acao;
		cmd.Parameters.Add("@dt_inicio", SqlDbType.DateTime).Value = _dt_inicio;
		cmd.Parameters.Add("@dt_fim", SqlDbType.DateTime).Value = _dt_fim;
		cmd.Parameters.Add("@dt_original", SqlDbType.DateTime).Value = _dt_original;
		cmd.Parameters.Add("@vl_previsto", SqlDbType.Decimal).Value = _vl_previsto;
		cmd.Parameters.Add("@vl_realizado", SqlDbType.Decimal).Value = _vl_realizado;
		cmd.Parameters.Add("@dt_cadastro", SqlDbType.DateTime).Value = _dt_cadastro;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch { throw; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}
    public bool UpdateMarcos()
    {
        SqlConnection sqlConn = new SqlConnection(pb.strConn());
        SqlCommand cmd = new SqlCommand("update t09_marco set dt_original=dt_prevista where fl_ativa=1 and " +
        "dt_original is null and t08_cd_acao in " +
        "(select t08_cd_acao from t08_acao where t03_cd_projeto=@t03_cd_projeto)", sqlConn);
        bool result;
        cmd.Parameters.Add("@t03_cd_projeto", SqlDbType.Int).Value = _t03_cd_projeto;

        try
        {
            sqlConn.Open();
            cmd.CommandType = CommandType.Text;
            result = Convert.ToBoolean(cmd.ExecuteNonQuery());
        }

        catch { throw; }

        finally
        {
            sqlConn.Close();
            cmd.Dispose();
            sqlConn.Dispose();
        }

        return result;
    }
	#endregion

	#region Delete

	public bool Delete()
	{
		SqlConnection sqlConn = new SqlConnection(pb.strConn());
		SqlCommand cmd = new SqlCommand("delete from t31_acaofase where", sqlConn);
		bool result;

		try
		{
			sqlConn.Open();
			cmd.CommandType = CommandType.Text;
			result = Convert.ToBoolean(cmd.ExecuteNonQuery());
		}

		catch { throw; }

		finally
		{
			sqlConn.Close();
			cmd.Dispose();
			sqlConn.Dispose();
		}

		return result;
	}

	#endregion

	#endregion
}
